-- SUPABASE SCHEMA FOR REVIVETEX
-- Run this in your Supabase SQL Editor to set up the database.

-- 1. PRODUCTS TABLE
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    price DECIMAL NOT NULL,
    imageurls TEXT[] DEFAULT '{}',
    moq INTEGER DEFAULT 1,
    stock_type TEXT DEFAULT 'semi-bulk',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

-- Clean up existing policies to avoid "already exists" errors
DROP POLICY IF EXISTS "Allow public read access" ON products;
DROP POLICY IF EXISTS "Allow public insert" ON products;
DROP POLICY IF EXISTS "Allow public update" ON products;
DROP POLICY IF EXISTS "Allow public delete" ON products;

-- Recreate policies (Permissive for initial setup)
CREATE POLICY "Allow public read access" ON products FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON products FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON products FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON products FOR DELETE USING (true);

-- 2. PROFILES TABLE
CREATE TABLE IF NOT EXISTS profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    business_name TEXT NOT NULL,
    owner_name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    address TEXT,
    location TEXT,
    business_type TEXT,
    is_verified BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view their own profile" ON profiles;
DROP POLICY IF EXISTS "Users can update their own profile" ON profiles;
DROP POLICY IF EXISTS "Allow profile creation during signup" ON profiles;

CREATE POLICY "Users can view their own profile" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Allow profile creation during signup" ON profiles FOR INSERT WITH CHECK (true);

-- 3. ORDERS TABLE
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id UUID REFERENCES auth.users ON DELETE SET NULL,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    address TEXT NOT NULL,
    paymentmethod TEXT NOT NULL,
    items JSONB NOT NULL,
    subtotal DECIMAL NOT NULL,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view their own orders" ON orders;
DROP POLICY IF EXISTS "Anyone can insert an order" ON orders;
DROP POLICY IF EXISTS "Public read for orders" ON orders;

CREATE POLICY "Users can view their own orders" ON orders FOR SELECT USING (auth.uid() = business_id);
CREATE POLICY "Anyone can insert an order" ON orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Public read for orders" ON orders FOR SELECT USING (true);

-- 4. STORAGE BUCKET
-- Note: You must create the 'product-images' bucket manually in the Supabase Storage UI.
-- Ensure it is set to 'Public'.
